version: '3'

services:
#   mongodb:
#     image: mongo:7
#     container_name: mongodb
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
  app-download-center:
    build: .
    env_file:
        - .env
    container_name: app-download-center
    restart: always
    ports:
      - "3000:3000"
    # 下面的配置允许在 Linux Docker 环境中使用 host.docker.internal 访问宿主机
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # 持久化存储上传的文件
      - ./data:/app/data
volumes:
  mongo_data:
